---
format:
  html:
    toc: true
    toc-depth: 5
    format-links: [pdf]
    css: ../styles.css
  typst: default
---

```{=typst}
#set text(font: "Noto Serif", lang: "el") // ensures bold + Greek shaping
    #let tbox(title, body) = rect(fill: luma(240), stroke: 1pt + gray, radius: 6pt, inset: 10pt)[
    #text(weight: "bold")[#title]
    #v(5pt)
    #body
  ]

#set list(indent: 18pt)
#set enum(indent: 18pt)
```

# Βασικές στατιστικές έννοιες

Η έρευνα στην εκπαίδευση κατά ένα πολύ σημαντικό μέρος της περιλαμβάνει τη
συλλογή πληροφοριών. Συνήθως, με τη λήξη συλλογής της πληροφορίας οι
ερευνητές/τριες καταλήγουν με έναν τεράστιο όγκο μετρήσεων είτε, παλιότερα, σε
χαρτί είτε σήμερα σε ηλεκτρονική μορφή. Για την επεξεργασία και αξιοποίηση αυτής
της πληροφορίας χρησιμοποιούνται μέθοδοι που συνοπτικά αποκαλούμε
"στατιστική". Η στατιστική μπορεί να χρησιμοποιηθεί τόσο για την οργάνωση και τη
συνόψιση της συγκεντρωμένης πληροφορίας όσο και για την συστηματική κατασκευή
μίας ερμηνείας της κατάστασης από την οποία η πληροφορία αυτή προέκυψε.

## Πληθυσμός και δείγμα

Κατά την εκτέλεση μίας μελέτης ο/η ερευνητής/τρια ξεκινά διατυπώνοντας ένα
γενικό ερώτημα για μία συγκεκριμένη ομάδα ανθρώπων που τον/την ενδιαφέρουν. Με
στατιστικούς όρους, το σύνολο όλων των ατόμων ενδιαφέροντος μίας μελέτης
ονομάζεται _πληθυσμός_. Για παράδειγμα, πληθυσμός σε μία εκπαιδευτική έρευνα θα
μπορούσε να είναι όλοι οι μαθητές νηπιαγωγείων της Δυτικής Μακεδονίας.

Προφανώς, σε μία μελέτη είναι πολύ δύσκολο να συλλεχθούν οι απαιτούμενες
πληροφορίες για το σύνολο του πληθυσμού ενδιαφέροντος, καθώς, τις περισσότερες
φορές, αυτός μπορεί να είναι απαγορευτικά μεγάλος. Οπότε, η αμέσως καλύτερη
προσέγγιση είναι να χρησιμοποιηθεί ένα υποσύνολο του πληθυσμού, με την ελπίδα
ότι αυτό θα "μοιάζει" με τον πληθυσμό. Ένα τέτοιο υποσύνολο ονομάζεται
_δείγμα_. Με στατιστικούς όρους, _δείγμα_ ονομάζεται ένα σύνολο ατόμων το οποίο
διαλέχτηκε από τον πληθυσμό με στόχο να τον αντιπροσωπεύσει σε μία ανάλυση.

Μία μελέτη εκπαιδευτικής έρευνας στοχεύει να περιγράψει ή να βγάλει συμπεράσματα
για συγκεκριμένα χαρακτηριστικά του πληθυσμού. Τα χαρακτηριστικά αυτά πρέπει να
είναι επακριβώς καθορισμένα και μετρήσιμα. Στη στατιστική, τα χαρακτηριστικά
αυτά αποκαλούνται _παράμετροι_. Επομένως, _παράμετρος_ είναι ένα χαρακτηριστικό
του πληθυσμού, άγνωστο αλλά μετρήσιμο.

Καθώς η γνώση της τιμής μιας παραμέτρου συνήθως απαιτεί τη λήψη μετρήσεων από το
σύνολο του πληθυσμού --- πράγμα συνήθως αδύνατο --- κατά την εκτέλεση
στατιστικών αναλύσεων αρκούμαστε στην εξαγωγή εκτιμήσεων για αυτήν την τιμή με
την αξιοίηση του δείγματος. Η _εκτίμηση_ της τιμής μιας παραμέτρου υπολογίζεται
συνήθως με τον συνδυασμό των μετρήσεων του δείγματος (π.χ. άθροισμα, μέσος
όρος). Με τη χρήση στατιστικής ορολογίας, ένας μαθηματικός συνδυασμός των
μετρήσεων ενός δείγματος από τον πληθυσμό ενδιαφέροντος ονομομάζεται
_στατιστικό_ ή _στατιστική συνάρτηση_ ή _δειγματοσυνάρτηση_.

## Μεταβλητές

_Μεταβλητή_ είναι οποιοδήποτε μετρήσιμο χαρακτηριστικό ατόμων ή πραγμάτων το
οποίο μπορεί να παίρνει διαφορετικές τιμές. Σε αντίθεση, μία _σταθερά_ είναι ένα
χαρακτηριστικό το οποίο πάιρνει μία και μοναδική τιμή σε ολόκληρο τον
πληθυσμό. Οι σταθερές, αν και φαίνεται ότι δεν έχουν ιδιαίτερο ενδιαφέρον, στην
πραγαμτικότητα αντικατοπτρίζουν τις αποφάσεις του ερευνητή/τριας για περιορισμό
του πληθυσμού ενδιαφέροντος. Για παράδειγμα, σε μία μελέτη με στόχο το σύνολο
των _μαθητριών_ στα νηπιαγωγεία της Δυτικής Μακεδονίας το φύλο είναι μία
σταθερά.

Οι μεταβλητές μπορούν να χωριστούν σε δύο κατηγορίες ανάλογα με τις τιμές που
μπορούν να λάβουν:

- Οι _διακριτές μεταβλητές_ παίρνουν τιμές μέσα από ένα σύνολο αδιαίρετων
  κατηγοριών πλήρως διαχωρίσιμων μεταξύ τους (π.χ. επίπεδο εκπαίδευσης γονέων,
  δήμος κατοικίας μαθητή, πλήθος μαθητών σε μία τάξη).
- Οι _συνεχείς μεταβλητές_ μπορούν να πάρουν οποιαδήποτε τιμή μέσα σε ένα
  σύνολο. Μεταξύ δύο πιθανών τιμών μίας συνεχούς μεταβλητής υπάρχει άπειρο
  πλήθος διαφορετικών δυνατών τιμών (π.χ. ηλικία διδάσκοντος, βάρος μαθητή).
  
Στην περίπτωση των συνεχών μεταβλητών (σε αντίθεση με τις διακριτές μεταβλητές),
είναι πολύ σπάνιο να μετρήσουμε την ίδια τιμή πολλές φορές σε ένα δείγμα που
έχουμε συλλέξει. Αν παρατηρήσουμε κάτι τέτοιο για μία συνεχή μεταβλητή που
μετρήσαμε, τότε θα πρέπει να αναθεωρήσουμε τον τρόπο μέτρησης της μεταβλητής ή
να επανεξετάσουμε αν η εν λόγω μεταβλητή είναι πράγματι συνεχής. Τέλος, καθώς η
ακρίβεια των εργαλείων που έχουμε για την μέτρηση των συνεχών μεταβλητών δεν
είναι τέλεια, θα πρέπει να αντιμετωπίζουμε τις τιμές των συνεχών μεταβλητών
περισσότερο ως διαστήματα και λιγότερο ως απόλυτες τιμές. Για παράδειγμα, αν το
βάρος δύο μαθητών μίας τάξης νηπιαγωγείου μετρηθεί ως 19 kg, δεν είναι λογικό να
υποθέσουμε ότι οι μαθητές έχουν το ίδιο ακριβώς βάρος. Το πιο σωστό θα ήταν να
θεωρήσουμε ότι και οι δύο μαθητές έχουν ένα βάρος μεταξύ π.χ. 18.5 και 19.5
κιλών. Το εύρος του διαστήματος αυτού εξαρτάται κατά κύριο λόγο από την ακρίβεια
της ζυγαριάς που χρησιμοποιήθηκε.

## Κλίμακες μέτρησης μεταβλητών

Η συλλογή των τιμών μίας μεταβλητής που παρατηρούνται σε ένα δείγμα με τον έναν
ή τον άλλον τρόπο προϋποθέτει τη μέτρηση με τη χρήση κάποιας κλίμακας. Για
παράδειγμα, το ύψος των μαθητών μίας τάξης μπορεί να μετρηθεί είτε
χρησιμοποιώντας τις κατηγορίες κοντός, μέτριος, ψηλός (διακριτή μεταβλητή) ή να
μετρηθεί με ακρίβεια εκατοστού (συνεχής μεταβλητή). Οι κλίμακες μέτρησης έχουν
μεγάλη σημασία γιατί επηρεάζουν τις στατιστικές μεθόδους που μπορούν να
χρησιμοποιηθούν για την ανάλυσή τους.

Η _ονομαστική κλίμακα_ ορίζει ως επιτρεπόμενες τιμές μίας μεταβλητής τα
_ονόματα_ διακριτών κατηγοριών. Οι κατηγορίες αυτές δεν μπορούν να διαταχθούν,
δηλαδή δεν μπορούμε να συγκρίνουμε τη μία τιμή με την άλλη. Αν και οι κατηγορίες
δεν είναι αριθμητικές μπορεί να παρουσιαστούν με αριθμητικές τιμές, π.χ. μπορεί
να χρησιμοποιηθεί ο αριθμός 1 για να δηλώσει ως τόπο κατοικίας του μαθητή τον
δήμο Φλώρινας και ο αριθμός 2 για να δηλώσει τον δήμο Καστορίας, χωρίς αυτό όμως
να υποδηλώνει κάποια διάταξη για τους δύο δήμους.

Αντίθετα, σε μία _διατάξιμη κλίμακα_ οι κατηγορίες παίρνουν τιμές η οποίες
υποδηλώνουν διάταξη. Για παράδειγμα, η οικονομική κατάσταση του σπιτικού των
μαθητών μίας τάξης θα μπορούσε να μετρηθεί χρησιμοποιώντας τις τιμές χαμηλή,
μέτρια, υψηλή. Οι τιμές παρόλο που επιτρέπουν τη σύγκριση μεταξύ των μετρήσεων
του δείγματος, δεν επιτρέπουν συμπεράσματα για το μέγεθος των διαφορών.

Τέλος, μεταβλητές που μετρήθηκαν χρησιμοποιώντας την _ισοδιαστημική κλίμακα_ ή
την _αναλογική κλίμακα_ επιτρέπουν την εξαγωγή συμπερασμάτων σχετικά με τη
διάταξη του δείγματος. Οι τιμές μίας μεταβλητής μετρημένης με μία _ισοδιαστημική
κλίμακα_ ιεραρχούνται και ταυτόχρονα τα διαστήματα μεταξύ διαδοχικών τιμών είναι
σταθερά και τα ίδια. Για παράδειγμα, η θερμοκρασία μίας αίθουσας τους
καλοκαιρινούς μήνες.

Η βασική διαφορά μίας ισοδιαστημικής κλίμακας από μία αναλογική κλίμακα, είναι
ότι στην πρώτη περίπτωση η τιμή 0 είναι αυθαίρετη. Για παράδειγμα, δεν μπορούμε
να πούμε ότι για δύο μετρήσεις θερμοκρασίας 20 και 40 βαθμών Κελσίου, η πρώτη
είναι διπλάσια από την δεύτερη. Αν άλλη κλίμακα είχε χρησιμποιηθεί
(π.χ. Fahrenheit) τότε ο λόγος των τιμών θα ήταν διαφορετικός. Σε μία _αναλογική
κλίμακα_, το 0 έχει σημασία και υποδηλώνει απουσία. Η ύπαρξη ενός απόλυτου 0,
υποδηλώνει ότι μπορούμε να μετρήσουμε το απόλυτο μέγεθος της μεταβλητής. Για
παράδειγμα ύψος ίσο με 0 σημαίνει απουσία ύψους και ύψος 120 εκατοστών είναι
διπλάσιο από το ύψος 60 εκατοστών. Το 0 σε αυτήν την περίπτωση δεν είναι
σχετικό, αλλά απόλυτο. Επομένως, η αναλογική κλίμακα είναι μία ισοδιαστημική
κλίμακα με την ύπαρξη ενός απόλυτου μηδέν.


## Μαθηματικοί συμβολισμοί

Συνήθως, στις στατιστικές αναλύσεις συμβολίζουμε τις τυχαίες μεταβλητές με
κεφαλαία γράμματα του λατινικού αλφαβήτου. Για παράδειγμα, μπορούμε να
συμβολίσουμε με $X$ το ύψος των μαθητών των νηπιαγωγείων της περιφέρειας Δυτικής
Μακεδονίας. Για συγκεκριμένες μετρήσεις της μεταβλητής $X$ χρησιμοποιούμε το
ίδιο _πεζό_ γράμμα ($x$). Για παράδειγμα, έστω ότι έχουμε ένα δείγμα μεγέθους $n
= 100$ από μαθητές των νηπιαγωγείων της περιφέρειας Δυτικής Μακεδονίας. Για κάθε
έναν από αυτούς τους μαθητές, συμβολίζουμε την μέτρηση του ύψους με
$x_i, i = 1,\dots,100$.

Με τις μετρήσεις μίας μεταβλητής $X$ συνήθως θέλουμε να κάνουμε πράξεις. Μία από
τις πιο συχνές ανάγκες που πορκύπτουν κατά την εκτέλεση μίας στατιστικής
ανάλυσης είναι να αθροίσουμε τις τιμές $x_i$ που συλλέχθηκαν. Ο μαθηματικός
συμβολισμός στην περίπτωση αυτή είναι το $\sum$. Στο προηγούμενο παράδειγμα, το
άθροισμα όλων των μετρήσεων του ύψους των 100 μαθητών θα μπορούσε να συμβολιστεί
με
$$
\sum X = \sum_{i = 1}^{100}x_i = x_1 + x_2 +\dots + x_100
$$
Οι πράξεις αυτές μπορούν να γίνουν αρκετά πιο σύνθετες, π.χ. να αθροίσουμε τα
τετράγωνα των μετρήσεων του ύψους ($\sum X^2$) ή να αθροίσουμε το ύψος τους μειωμένο κατά μία
μονάδα ($\sum (X-1)$).
