---
format:
  html:
    toc: true
    toc-depth: 5
    format-links: [pdf]
    css: ../styles.css
  typst: default
---

```{=typst}

#set text(font: "Noto Serif", lang: "el") // ensures bold + Greek shaping
    #let tbox(title, body) = rect(fill: luma(240), stroke: 1pt + gray, radius: 6pt, inset: 10pt)[
    #text(weight: "bold")[#title]
    #v(5pt)
    #body
  ]

```

# Μέτρα θέσης

Τα μέτρα θέσης χρησιμοποιούνται για να περιγράψουν με τη χρήση ενός μόνο αριθμού
το κέντρο της κατανομής των τιμών μίας τυχαίας μεταβλητής. Με απλά λόγια, τα
μέτρα θέσης περιγράφουν γύρω από ποια τιμή συγκεντρώνονται οι τιμές μίας τυχαίας
μεταβλητής που μετρήθηκε κατά την εκτέλεση μίας μελέτης. Δυστυχώς, δεν υπάρχει
ένας μοναδικός τρόπος που να μας δίνει με τον καλύτερο τρόπο τη θέση των τιμών
μίας μεταβλητής. Στη συνέχεια θα δούμε τρεις μεθόδους για τον υπολογισμό της
θέσης: τη μέση τιμή, τη διάμεσο και την επικρατούσα τιμή.

## Μέση τιμή

Η μέση τιμή για την κατανομή των τιμών μίας τυχαίας μεταβλητής υπολογίζεται ως
μέσος όρος των τιμών της, δηλαδή αθροίζοντας όλες τις τιμές και διαιρώντας με το
πλήθος τους:

$$
\mu = \frac{\sum X}{N}
$$

Καθώς η μέση τιμή υπολογίζεται με τη χρήση $\sum X$ και με το $N$ μπορούμε να
την υπολογίσουμε ακόμα κι αν δεν έχουμε τις αρχικές μετρήσεις αλλά τον πίνακα
συχντοτήτων των μετρήσεων για μία μεταβλητή. Για παράδειγμα, έστω ότι σε μία
μελέτη ο/η ερευνητής/τρια θέλησε να αξιολογήσει τις κινητικές δεξιότητες των
μαθητών μίας τάξης νηπιαγωγείου δίνοντάς τους 4 τουβλάκια και ζητώντας τους να
τα τοποθετήσουν το ένα πάνω στο άλλο φτιάχνοντας έναν πύργο. Έστω $X$ η
μεταβλητή "το πλήθος από τουβλάκια που χρησιμοποίησε ο μαθητής για τον πύργο
του". Ο πίνακας συχνοτήτων των μετρήσεων της μεταβλητής $X$ φαίνεται στον
παρακάτω πίνακα.


```{=typst}
#align(center)[
  #table(
    columns: 2,
    align: center,
    table.header([*x*], [*f*]),
    [1], [1],
    [2], [4],
    [3], [9],
    [4], [6]
  )
]
```

Για τον υπολογισμό της μέσης τιμής της $X$ θα χρειαστούμε το άθροισμα 
$$
\sum X = \sum_{i=1}^4 f(x_i)x_i = 1\times 1 + 4\times 2 + 9\times 3 + 6\times 4 = 60
$$

Επίσης θα χρειαστούμε το μέγεθος του δείγματος $N$ το οποίο μπορούμε να βρούμε αθροίζοντας όλες τις συχνότητες
$$
N = \sum_{i=1}^4f(i) = 1 + 4 + 9 + 6 = 20
$$

Επομένως, η μέση τιμή $\mu$ μπορεί να υπολογιστεί από

$$
\mu = \frac{\sum X}{N} = \frac{\sum_{i=1}^4f(x_i)x_i}{\sum_{i=1}^4f(i)} = \frac{60}{20} = 3
$$

Αν και η μέση τιμή είναι η πιο εύληπτη μέθοδος για τον υπολογισμό της θέσης των
μετρήσεων μιας μεταβλητής, έχει ένα σημαντικό μειονέκτημα. Στην περίπτωση που
υπάρχουν ακραίες τιμές η μέση τιμή μπορεί να επηρεαστεί τόσο πολύ, ώστε το
αποτέλεσμα να μην είναι αντιπροσωπευτικό του δείγματος. Για παράδειγμα, έστω ότι
μετράμε τη μέση ηλικία σε μια αίθουσα νηπιαγωγείου. Η αίθουσα έχει 4 μαθητές ηλικίας 5
ετών και έναν δάσκαλο ηλικίας 60 ετών. Τότε, η μέση ηλικία στην αίθουσα είναι 
$$
\mu = \frac{4\times 5 + 60}{5} = \frac{80}{5} = 16
$$

Στη συγκεκριμένη περίπτωση, η τιμή 16 δεν αντιπροσωπεύει κανέναν. Το νούμερο
είναι πολύ μεγάλο για όλους τους μαθητές της αίθουσας και πολύ μικρό για τον
δάσκαλο. Είναι σημαντικό να θυμόμαστε ότι σκοπός των μέτρων θέσης είναι να μας
δώσουν την τιμή εκείνη γύρω από την οποία συγκεντρώνεται η πλειοψηφία των τιμών
μίας μεταβλητής, ώστε να μπορέσουμε να αντιπροσωπεύσουμε όλες τις μετρήσεις με
έναν αριθμό. Συμβαίνει αυτό στο συγκεκριμένο παράδειγμα;
