name: Render and Publish
on:
  push:
    branches: [main, develop]
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.2'
      - name: Install R Dependencies
        uses: r-lib/actions/setup-renv@v2
      
      - name: Install Noto Fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-noto fonts-noto-mono
          fc-cache -f -v
      
      - name: Install Typst
        run: |
          wget https://github.com/typst/typst/releases/download/v0.11.0/typst-x86_64-unknown-linux-musl.tar.xz
          tar -xf typst-x86_64-unknown-linux-musl.tar.xz
          sudo mv typst-x86_64-unknown-linux-musl/typst /usr/local/bin/
          typst --version
      
      - name: Install TinyTeX
        run: quarto install tinytex
      
      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2
      # Deploy main branch to root of gh-pages
      - name: Deploy main branch
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages
      # Deploy develop branch to /develop/ subdirectory of gh-pages
      - name: Deploy develop branch  
        if: github.ref == 'refs/heads/develop'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          destination_dir: develop
          publish_branch: gh-pages
          keep_files: true